package com.sap.s4hana.sample.validation;

import javax.validation.groups.Default;

import com.sap.s4hana.sample.print.model.PrintTask;

/**
 * Bean Validation group used to customize validation of
 * {@link PrintTask#getPrintContents()}:
 * <ul>
 * <li>it is mandatory when printing an existing file (one must provide a name)
 * <li>but not needed when rendering a document (filename is generated by ADS
 * Forms by Adobe service when rendering a document)
 * </ul>
 *
 */
public interface ForPrinting extends Default {

}
